### ISSUE TITLE
!! Transfer to Silverflag org repo

### ISSUE THREAD

**Issue by efenow** [YetAnotherNotHacking/w95sf#2]

**Comment by YetAnotherNotHacking** [comment]
ill get to it at some point, though most of the code that gives it a point will need to be re-written

I changed all of the urls for the tools which were hard coded in the files
I changed all of the UIs which will not display correctly currently
This lacks basic features.

**Comment by YetAnotherNotHacking** [comment]
actually now that I think about it it is in sf-clearnet in the w95 folder
